//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersPortal.Services.WebPortalOrderBillService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://cportal_bill.vs", ConfigurationName="WebPortalOrderBillService.cportal_bill_vsPortType")]
    public interface cportal_bill_vsPortType {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cportal_bill.vs#cportal_bill_vs:get_customer_bill_info", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_infoResponse get_customer_bill_info(OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_infoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cportal_bill.vs#cportal_bill_vs:get_customer_bill_info", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_infoResponse> get_customer_bill_infoAsync(OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_infoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cportal_bill.vs#cportal_bill_vs:set_customer_bill", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        bool set_customer_bill(OrdersPortal.Services.WebPortalOrderBillService.Create1COrder DTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cportal_bill.vs#cportal_bill_vs:set_customer_bill", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<bool> set_customer_billAsync(OrdersPortal.Services.WebPortalOrderBillService.Create1COrder DTO);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayItemAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://cportal_bill.vs#cportal_bill_vs:get_customer_bill_list", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_listResponse get_customer_bill_list(OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_listRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cportal_bill.vs#cportal_bill_vs:get_customer_bill_list", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_listResponse> get_customer_bill_listAsync(OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_listRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cportal_bill.vs#cportal_bill_vs:get_customer_bill_PDF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string get_customer_bill_PDF(string bill_GUID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://cportal_bill.vs#cportal_bill_vs:get_customer_bill_PDF", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<string> get_customer_bill_PDFAsync(string bill_GUID);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cportal_bill.vs")]
    public partial class CustomerOrderDATA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string tYPEField;
        
        private string gUIDField;
        
        private string nAMEField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
                this.RaisePropertyChanged("TYPE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string NAME {
            get {
                return this.nAMEField;
            }
            set {
                this.nAMEField = value;
                this.RaisePropertyChanged("NAME");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cportal_bill.vs")]
    public partial class bill_listDATA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gUIDField;
        
        private string numberField;
        
        private System.DateTime dateField;
        
        private double bill_sumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GUID {
            get {
                return this.gUIDField;
            }
            set {
                this.gUIDField = value;
                this.RaisePropertyChanged("GUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public double bill_sum {
            get {
                return this.bill_sumField;
            }
            set {
                this.bill_sumField = value;
                this.RaisePropertyChanged("bill_sum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cportal_bill.vs")]
    public partial class OrderItemsDATA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string itemGUIDField;
        
        private double priceField;
        
        private double countField;
        
        private System.Nullable<int> heightField;
        
        private System.Nullable<int> widthField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ItemGUID {
            get {
                return this.itemGUIDField;
            }
            set {
                this.itemGUIDField = value;
                this.RaisePropertyChanged("ItemGUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public double Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public double Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
                this.RaisePropertyChanged("Count");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<int> Height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("Height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<int> Width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("Width");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cportal_bill.vs")]
    public partial class Create1COrder : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderNumberField;
        
        private string orderContrAgentField;
        
        private string orderIbanField;
        
        private System.DateTime orderCreateDateField;
        
        private System.DateTime orderDeliveryDateField;
        
        private string addressField;
        
        private double orderSumaField;
        
        private string internalCommentField;
        
        private OrderItemsDATA[] orderItemsLISTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string OrderNumber {
            get {
                return this.orderNumberField;
            }
            set {
                this.orderNumberField = value;
                this.RaisePropertyChanged("OrderNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OrderContrAgent {
            get {
                return this.orderContrAgentField;
            }
            set {
                this.orderContrAgentField = value;
                this.RaisePropertyChanged("OrderContrAgent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OrderIban {
            get {
                return this.orderIbanField;
            }
            set {
                this.orderIbanField = value;
                this.RaisePropertyChanged("OrderIban");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime OrderCreateDate {
            get {
                return this.orderCreateDateField;
            }
            set {
                this.orderCreateDateField = value;
                this.RaisePropertyChanged("OrderCreateDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime OrderDeliveryDate {
            get {
                return this.orderDeliveryDateField;
            }
            set {
                this.orderDeliveryDateField = value;
                this.RaisePropertyChanged("OrderDeliveryDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public double OrderSuma {
            get {
                return this.orderSumaField;
            }
            set {
                this.orderSumaField = value;
                this.RaisePropertyChanged("OrderSuma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string InternalComment {
            get {
                return this.internalCommentField;
            }
            set {
                this.internalCommentField = value;
                this.RaisePropertyChanged("InternalComment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderItemsLIST", Order=8)]
        public OrderItemsDATA[] OrderItemsLIST {
            get {
                return this.orderItemsLISTField;
            }
            set {
                this.orderItemsLISTField = value;
                this.RaisePropertyChanged("OrderItemsLIST");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_customer_bill_info", WrapperNamespace="http://cportal_bill.vs", IsWrapped=true)]
    public partial class get_customer_bill_infoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cportal_bill.vs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kontr_kod;
        
        public get_customer_bill_infoRequest() {
        }
        
        public get_customer_bill_infoRequest(string kontr_kod) {
            this.kontr_kod = kontr_kod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_customer_bill_infoResponse", WrapperNamespace="http://cportal_bill.vs", IsWrapped=true)]
    public partial class get_customer_bill_infoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cportal_bill.vs", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LIST", IsNullable=false)]
        public OrdersPortal.Services.WebPortalOrderBillService.CustomerOrderDATA[] @return;
        
        public get_customer_bill_infoResponse() {
        }
        
        public get_customer_bill_infoResponse(OrdersPortal.Services.WebPortalOrderBillService.CustomerOrderDATA[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_customer_bill_list", WrapperNamespace="http://cportal_bill.vs", IsWrapped=true)]
    public partial class get_customer_bill_listRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cportal_bill.vs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string kontr_kod;
        
        public get_customer_bill_listRequest() {
        }
        
        public get_customer_bill_listRequest(string kontr_kod) {
            this.kontr_kod = kontr_kod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="get_customer_bill_listResponse", WrapperNamespace="http://cportal_bill.vs", IsWrapped=true)]
    public partial class get_customer_bill_listResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://cportal_bill.vs", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("LIST", IsNullable=false)]
        public OrdersPortal.Services.WebPortalOrderBillService.bill_listDATA[] @return;
        
        public get_customer_bill_listResponse() {
        }
        
        public get_customer_bill_listResponse(OrdersPortal.Services.WebPortalOrderBillService.bill_listDATA[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface cportal_bill_vsPortTypeChannel : OrdersPortal.Services.WebPortalOrderBillService.cportal_bill_vsPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class cportal_bill_vsPortTypeClient : System.ServiceModel.ClientBase<OrdersPortal.Services.WebPortalOrderBillService.cportal_bill_vsPortType>, OrdersPortal.Services.WebPortalOrderBillService.cportal_bill_vsPortType {
        
        public cportal_bill_vsPortTypeClient() {
        }
        
        public cportal_bill_vsPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public cportal_bill_vsPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cportal_bill_vsPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public cportal_bill_vsPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_infoResponse OrdersPortal.Services.WebPortalOrderBillService.cportal_bill_vsPortType.get_customer_bill_info(OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_infoRequest request) {
            return base.Channel.get_customer_bill_info(request);
        }
        
        public OrdersPortal.Services.WebPortalOrderBillService.CustomerOrderDATA[] get_customer_bill_info(string kontr_kod) {
            OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_infoRequest inValue = new OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_infoRequest();
            inValue.kontr_kod = kontr_kod;
            OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_infoResponse retVal = ((OrdersPortal.Services.WebPortalOrderBillService.cportal_bill_vsPortType)(this)).get_customer_bill_info(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_infoResponse> OrdersPortal.Services.WebPortalOrderBillService.cportal_bill_vsPortType.get_customer_bill_infoAsync(OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_infoRequest request) {
            return base.Channel.get_customer_bill_infoAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_infoResponse> get_customer_bill_infoAsync(string kontr_kod) {
            OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_infoRequest inValue = new OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_infoRequest();
            inValue.kontr_kod = kontr_kod;
            return ((OrdersPortal.Services.WebPortalOrderBillService.cportal_bill_vsPortType)(this)).get_customer_bill_infoAsync(inValue);
        }
        
        public bool set_customer_bill(OrdersPortal.Services.WebPortalOrderBillService.Create1COrder DTO) {
            return base.Channel.set_customer_bill(DTO);
        }
        
        public System.Threading.Tasks.Task<bool> set_customer_billAsync(OrdersPortal.Services.WebPortalOrderBillService.Create1COrder DTO) {
            return base.Channel.set_customer_billAsync(DTO);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_listResponse OrdersPortal.Services.WebPortalOrderBillService.cportal_bill_vsPortType.get_customer_bill_list(OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_listRequest request) {
            return base.Channel.get_customer_bill_list(request);
        }
        
        public OrdersPortal.Services.WebPortalOrderBillService.bill_listDATA[] get_customer_bill_list(string kontr_kod) {
            OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_listRequest inValue = new OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_listRequest();
            inValue.kontr_kod = kontr_kod;
            OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_listResponse retVal = ((OrdersPortal.Services.WebPortalOrderBillService.cportal_bill_vsPortType)(this)).get_customer_bill_list(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_listResponse> OrdersPortal.Services.WebPortalOrderBillService.cportal_bill_vsPortType.get_customer_bill_listAsync(OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_listRequest request) {
            return base.Channel.get_customer_bill_listAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_listResponse> get_customer_bill_listAsync(string kontr_kod) {
            OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_listRequest inValue = new OrdersPortal.Services.WebPortalOrderBillService.get_customer_bill_listRequest();
            inValue.kontr_kod = kontr_kod;
            return ((OrdersPortal.Services.WebPortalOrderBillService.cportal_bill_vsPortType)(this)).get_customer_bill_listAsync(inValue);
        }
        
        public string get_customer_bill_PDF(string bill_GUID) {
            return base.Channel.get_customer_bill_PDF(bill_GUID);
        }
        
        public System.Threading.Tasks.Task<string> get_customer_bill_PDFAsync(string bill_GUID) {
            return base.Channel.get_customer_bill_PDFAsync(bill_GUID);
        }
    }
}
