//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersPortal.Services.WebPortalComplaints1cService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="issues_list", Namespace="http://complaints", ItemName="data_list")]
    [System.SerializableAttribute()]
    public class issues_list : System.Collections.Generic.List<OrdersPortal.Services.WebPortalComplaints1cService.issues_data> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="issues_data", Namespace="http://complaints")]
    [System.SerializableAttribute()]
    public partial class issues_data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string GUIDField;
        
        private string NameField;
        
        private string ParentNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GUIDField, value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ParentName {
            get {
                return this.ParentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ParentNameField, value) != true)) {
                    this.ParentNameField = value;
                    this.RaisePropertyChanged("ParentName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://complaints", ConfigurationName="WebPortalComplaints1cService.complaintsPortType")]
    public interface complaintsPortType {
        
        // CODEGEN: Generating message contract since element name OrderNumber from namespace http://complaints is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://complaints#complaints:check_kontr_order", ReplyAction="*")]
        OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderResponse check_kontr_order(OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://complaints#complaints:check_kontr_order", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderResponse> check_kontr_orderAsync(OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderRequest request);
        
        // CODEGEN: Generating message contract since element name return from namespace http://complaints is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://complaints#complaints:getComplaintIssuesList", ReplyAction="*")]
        OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListResponse getComplaintIssuesList(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://complaints#complaints:getComplaintIssuesList", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListResponse> getComplaintIssuesListAsync(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListRequest request);
        
        // CODEGEN: Generating message contract since element name issueId from namespace http://complaints is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://complaints#complaints:getComplaintSolutionsListByIssue", ReplyAction="*")]
        OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueResponse getComplaintSolutionsListByIssue(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://complaints#complaints:getComplaintSolutionsListByIssue", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueResponse> getComplaintSolutionsListByIssueAsync(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueRequest request);
        
        // CODEGEN: Generating message contract since element name OrderNumber from namespace http://complaints is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://complaints#complaints:getComplaintSeries", ReplyAction="*")]
        OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesResponse getComplaintSeries(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://complaints#complaints:getComplaintSeries", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesResponse> getComplaintSeriesAsync(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class check_kontr_orderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="check_kontr_order", Namespace="http://complaints", Order=0)]
        public OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderRequestBody Body;
        
        public check_kontr_orderRequest() {
        }
        
        public check_kontr_orderRequest(OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://complaints")]
    public partial class check_kontr_orderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OrderNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string KontrKod;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime BeginDate;
        
        public check_kontr_orderRequestBody() {
        }
        
        public check_kontr_orderRequestBody(string OrderNumber, string KontrKod, System.DateTime BeginDate) {
            this.OrderNumber = OrderNumber;
            this.KontrKod = KontrKod;
            this.BeginDate = BeginDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class check_kontr_orderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="check_kontr_orderResponse", Namespace="http://complaints", Order=0)]
        public OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderResponseBody Body;
        
        public check_kontr_orderResponse() {
        }
        
        public check_kontr_orderResponse(OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://complaints")]
    public partial class check_kontr_orderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public check_kontr_orderResponseBody() {
        }
        
        public check_kontr_orderResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getComplaintIssuesListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getComplaintIssuesList", Namespace="http://complaints", Order=0)]
        public OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListRequestBody Body;
        
        public getComplaintIssuesListRequest() {
        }
        
        public getComplaintIssuesListRequest(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getComplaintIssuesListRequestBody {
        
        public getComplaintIssuesListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getComplaintIssuesListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getComplaintIssuesListResponse", Namespace="http://complaints", Order=0)]
        public OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListResponseBody Body;
        
        public getComplaintIssuesListResponse() {
        }
        
        public getComplaintIssuesListResponse(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://complaints")]
    public partial class getComplaintIssuesListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OrdersPortal.Services.WebPortalComplaints1cService.issues_list @return;
        
        public getComplaintIssuesListResponseBody() {
        }
        
        public getComplaintIssuesListResponseBody(OrdersPortal.Services.WebPortalComplaints1cService.issues_list @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getComplaintSolutionsListByIssueRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getComplaintSolutionsListByIssue", Namespace="http://complaints", Order=0)]
        public OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueRequestBody Body;
        
        public getComplaintSolutionsListByIssueRequest() {
        }
        
        public getComplaintSolutionsListByIssueRequest(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://complaints")]
    public partial class getComplaintSolutionsListByIssueRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string issueId;
        
        public getComplaintSolutionsListByIssueRequestBody() {
        }
        
        public getComplaintSolutionsListByIssueRequestBody(string issueId) {
            this.issueId = issueId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getComplaintSolutionsListByIssueResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getComplaintSolutionsListByIssueResponse", Namespace="http://complaints", Order=0)]
        public OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueResponseBody Body;
        
        public getComplaintSolutionsListByIssueResponse() {
        }
        
        public getComplaintSolutionsListByIssueResponse(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://complaints")]
    public partial class getComplaintSolutionsListByIssueResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OrdersPortal.Services.WebPortalComplaints1cService.issues_list @return;
        
        public getComplaintSolutionsListByIssueResponseBody() {
        }
        
        public getComplaintSolutionsListByIssueResponseBody(OrdersPortal.Services.WebPortalComplaints1cService.issues_list @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getComplaintSeriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getComplaintSeries", Namespace="http://complaints", Order=0)]
        public OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesRequestBody Body;
        
        public getComplaintSeriesRequest() {
        }
        
        public getComplaintSeriesRequest(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://complaints")]
    public partial class getComplaintSeriesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string OrderNumber;
        
        public getComplaintSeriesRequestBody() {
        }
        
        public getComplaintSeriesRequestBody(string OrderNumber) {
            this.OrderNumber = OrderNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getComplaintSeriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getComplaintSeriesResponse", Namespace="http://complaints", Order=0)]
        public OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesResponseBody Body;
        
        public getComplaintSeriesResponse() {
        }
        
        public getComplaintSeriesResponse(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://complaints")]
    public partial class getComplaintSeriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OrdersPortal.Services.WebPortalComplaints1cService.issues_list @return;
        
        public getComplaintSeriesResponseBody() {
        }
        
        public getComplaintSeriesResponseBody(OrdersPortal.Services.WebPortalComplaints1cService.issues_list @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface complaintsPortTypeChannel : OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class complaintsPortTypeClient : System.ServiceModel.ClientBase<OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType>, OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType {
        
        public complaintsPortTypeClient() {
        }
        
        public complaintsPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public complaintsPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public complaintsPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public complaintsPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderResponse OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType.check_kontr_order(OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderRequest request) {
            return base.Channel.check_kontr_order(request);
        }
        
        public bool check_kontr_order(string OrderNumber, string KontrKod, System.DateTime BeginDate) {
            OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderRequest inValue = new OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderRequest();
            inValue.Body = new OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderRequestBody();
            inValue.Body.OrderNumber = OrderNumber;
            inValue.Body.KontrKod = KontrKod;
            inValue.Body.BeginDate = BeginDate;
            OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderResponse retVal = ((OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType)(this)).check_kontr_order(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderResponse> OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType.check_kontr_orderAsync(OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderRequest request) {
            return base.Channel.check_kontr_orderAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderResponse> check_kontr_orderAsync(string OrderNumber, string KontrKod, System.DateTime BeginDate) {
            OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderRequest inValue = new OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderRequest();
            inValue.Body = new OrdersPortal.Services.WebPortalComplaints1cService.check_kontr_orderRequestBody();
            inValue.Body.OrderNumber = OrderNumber;
            inValue.Body.KontrKod = KontrKod;
            inValue.Body.BeginDate = BeginDate;
            return ((OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType)(this)).check_kontr_orderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListResponse OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType.getComplaintIssuesList(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListRequest request) {
            return base.Channel.getComplaintIssuesList(request);
        }
        
        public OrdersPortal.Services.WebPortalComplaints1cService.issues_list getComplaintIssuesList() {
            OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListRequest inValue = new OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListRequest();
            inValue.Body = new OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListRequestBody();
            OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListResponse retVal = ((OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType)(this)).getComplaintIssuesList(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListResponse> OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType.getComplaintIssuesListAsync(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListRequest request) {
            return base.Channel.getComplaintIssuesListAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListResponse> getComplaintIssuesListAsync() {
            OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListRequest inValue = new OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListRequest();
            inValue.Body = new OrdersPortal.Services.WebPortalComplaints1cService.getComplaintIssuesListRequestBody();
            return ((OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType)(this)).getComplaintIssuesListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueResponse OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType.getComplaintSolutionsListByIssue(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueRequest request) {
            return base.Channel.getComplaintSolutionsListByIssue(request);
        }
        
        public OrdersPortal.Services.WebPortalComplaints1cService.issues_list getComplaintSolutionsListByIssue(string issueId) {
            OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueRequest inValue = new OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueRequest();
            inValue.Body = new OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueRequestBody();
            inValue.Body.issueId = issueId;
            OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueResponse retVal = ((OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType)(this)).getComplaintSolutionsListByIssue(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueResponse> OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType.getComplaintSolutionsListByIssueAsync(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueRequest request) {
            return base.Channel.getComplaintSolutionsListByIssueAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueResponse> getComplaintSolutionsListByIssueAsync(string issueId) {
            OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueRequest inValue = new OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueRequest();
            inValue.Body = new OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSolutionsListByIssueRequestBody();
            inValue.Body.issueId = issueId;
            return ((OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType)(this)).getComplaintSolutionsListByIssueAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesResponse OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType.getComplaintSeries(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesRequest request) {
            return base.Channel.getComplaintSeries(request);
        }
        
        public OrdersPortal.Services.WebPortalComplaints1cService.issues_list getComplaintSeries(string OrderNumber) {
            OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesRequest inValue = new OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesRequest();
            inValue.Body = new OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesRequestBody();
            inValue.Body.OrderNumber = OrderNumber;
            OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesResponse retVal = ((OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType)(this)).getComplaintSeries(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesResponse> OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType.getComplaintSeriesAsync(OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesRequest request) {
            return base.Channel.getComplaintSeriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesResponse> getComplaintSeriesAsync(string OrderNumber) {
            OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesRequest inValue = new OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesRequest();
            inValue.Body = new OrdersPortal.Services.WebPortalComplaints1cService.getComplaintSeriesRequestBody();
            inValue.Body.OrderNumber = OrderNumber;
            return ((OrdersPortal.Services.WebPortalComplaints1cService.complaintsPortType)(this)).getComplaintSeriesAsync(inValue);
        }
    }
}
