//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersPortal.Services.WebOrder1cService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="group_list", Namespace="http://weborder", ItemName="group_data_list")]
    [System.SerializableAttribute()]
    public class group_list : System.Collections.Generic.List<OrdersPortal.Services.WebOrder1cService.group_data> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="group_data", Namespace="http://weborder")]
    [System.SerializableAttribute()]
    public partial class group_data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _1c_IDField;
        
        private string _1c_NameField;
        
        private string _1c_TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string _1c_ID {
            get {
                return this._1c_IDField;
            }
            set {
                if ((object.ReferenceEquals(this._1c_IDField, value) != true)) {
                    this._1c_IDField = value;
                    this.RaisePropertyChanged("_1c_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string _1c_Name {
            get {
                return this._1c_NameField;
            }
            set {
                if ((object.ReferenceEquals(this._1c_NameField, value) != true)) {
                    this._1c_NameField = value;
                    this.RaisePropertyChanged("_1c_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string _1c_Type {
            get {
                return this._1c_TypeField;
            }
            set {
                if ((object.ReferenceEquals(this._1c_TypeField, value) != true)) {
                    this._1c_TypeField = value;
                    this.RaisePropertyChanged("_1c_Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="complectations_list", Namespace="http://weborder", ItemName="complectations_data_list")]
    [System.SerializableAttribute()]
    public class complectations_list : System.Collections.Generic.List<OrdersPortal.Services.WebOrder1cService.complectations_data> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="complectations_data", Namespace="http://weborder")]
    [System.SerializableAttribute()]
    public partial class complectations_data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _1c_IDField;
        
        private string _1c_nameField;
        
        private string _1c_parent_IDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string _1c_ID {
            get {
                return this._1c_IDField;
            }
            set {
                if ((object.ReferenceEquals(this._1c_IDField, value) != true)) {
                    this._1c_IDField = value;
                    this.RaisePropertyChanged("_1c_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string _1c_name {
            get {
                return this._1c_nameField;
            }
            set {
                if ((object.ReferenceEquals(this._1c_nameField, value) != true)) {
                    this._1c_nameField = value;
                    this.RaisePropertyChanged("_1c_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string _1c_parent_ID {
            get {
                return this._1c_parent_IDField;
            }
            set {
                if ((object.ReferenceEquals(this._1c_parent_IDField, value) != true)) {
                    this._1c_parent_IDField = value;
                    this.RaisePropertyChanged("_1c_parent_ID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="nom_list", Namespace="http://weborder", ItemName="nom_data_list")]
    [System.SerializableAttribute()]
    public class nom_list : System.Collections.Generic.List<OrdersPortal.Services.WebOrder1cService.nom_data> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="nom_data", Namespace="http://weborder")]
    [System.SerializableAttribute()]
    public partial class nom_data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _1c_IDField;
        
        private string _1c_nameField;
        
        private string _1c_groupField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string _1c_ID {
            get {
                return this._1c_IDField;
            }
            set {
                if ((object.ReferenceEquals(this._1c_IDField, value) != true)) {
                    this._1c_IDField = value;
                    this.RaisePropertyChanged("_1c_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string _1c_name {
            get {
                return this._1c_nameField;
            }
            set {
                if ((object.ReferenceEquals(this._1c_nameField, value) != true)) {
                    this._1c_nameField = value;
                    this.RaisePropertyChanged("_1c_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string _1c_group {
            get {
                return this._1c_groupField;
            }
            set {
                if ((object.ReferenceEquals(this._1c_groupField, value) != true)) {
                    this._1c_groupField = value;
                    this.RaisePropertyChanged("_1c_group");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="nom_vs_comp_list", Namespace="http://weborder", ItemName="data_list")]
    [System.SerializableAttribute()]
    public class nom_vs_comp_list : System.Collections.Generic.List<OrdersPortal.Services.WebOrder1cService.nom_vs_comp_data> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="nom_vs_comp_data", Namespace="http://weborder")]
    [System.SerializableAttribute()]
    public partial class nom_vs_comp_data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string _1c_ID_nomField;
        
        private string _1c_ID_compField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string _1c_ID_nom {
            get {
                return this._1c_ID_nomField;
            }
            set {
                if ((object.ReferenceEquals(this._1c_ID_nomField, value) != true)) {
                    this._1c_ID_nomField = value;
                    this.RaisePropertyChanged("_1c_ID_nom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string _1c_ID_comp {
            get {
                return this._1c_ID_compField;
            }
            set {
                if ((object.ReferenceEquals(this._1c_ID_compField, value) != true)) {
                    this._1c_ID_compField = value;
                    this.RaisePropertyChanged("_1c_ID_comp");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContractSumm", Namespace="http://weborder")]
    [System.SerializableAttribute()]
    public partial class ContractSumm : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ContractField;
        
        private double SummField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string Contract {
            get {
                return this.ContractField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractField, value) != true)) {
                    this.ContractField = value;
                    this.RaisePropertyChanged("Contract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Summ {
            get {
                return this.SummField;
            }
            set {
                if ((this.SummField.Equals(value) != true)) {
                    this.SummField = value;
                    this.RaisePropertyChanged("Summ");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="PaymentDocumentDataList", Namespace="http://weborder", ItemName="data")]
    [System.SerializableAttribute()]
    public class PaymentDocumentDataList : System.Collections.Generic.List<OrdersPortal.Services.WebOrder1cService.PaymentDocumentData> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PaymentDocumentData", Namespace="http://weborder")]
    [System.SerializableAttribute()]
    public partial class PaymentDocumentData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string order_numberField;
        
        private double pay_sumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string order_number {
            get {
                return this.order_numberField;
            }
            set {
                if ((object.ReferenceEquals(this.order_numberField, value) != true)) {
                    this.order_numberField = value;
                    this.RaisePropertyChanged("order_number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double pay_sum {
            get {
                return this.pay_sumField;
            }
            set {
                if ((this.pay_sumField.Equals(value) != true)) {
                    this.pay_sumField = value;
                    this.RaisePropertyChanged("pay_sum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://weborder", ConfigurationName="WebOrder1cService.WebOrderPortType")]
    public interface WebOrderPortType {
        
        // CODEGEN: Generating message contract since element name return from namespace http://weborder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetNomenklaturaGroup", ReplyAction="*")]
        OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupResponse GetNomenklaturaGroup(OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetNomenklaturaGroup", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupResponse> GetNomenklaturaGroupAsync(OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupRequest request);
        
        // CODEGEN: Generating message contract since element name return from namespace http://weborder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetComplectation", ReplyAction="*")]
        OrdersPortal.Services.WebOrder1cService.GetComplectationResponse GetComplectation(OrdersPortal.Services.WebOrder1cService.GetComplectationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetComplectation", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetComplectationResponse> GetComplectationAsync(OrdersPortal.Services.WebOrder1cService.GetComplectationRequest request);
        
        // CODEGEN: Generating message contract since element name return from namespace http://weborder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetNomenklatura", ReplyAction="*")]
        OrdersPortal.Services.WebOrder1cService.GetNomenklaturaResponse GetNomenklatura(OrdersPortal.Services.WebOrder1cService.GetNomenklaturaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetNomenklatura", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetNomenklaturaResponse> GetNomenklaturaAsync(OrdersPortal.Services.WebOrder1cService.GetNomenklaturaRequest request);
        
        // CODEGEN: Generating message contract since element name return from namespace http://weborder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetNomVSComp", ReplyAction="*")]
        OrdersPortal.Services.WebOrder1cService.GetNomVSCompResponse GetNomVSComp(OrdersPortal.Services.WebOrder1cService.GetNomVSCompRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetNomVSComp", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetNomVSCompResponse> GetNomVSCompAsync(OrdersPortal.Services.WebOrder1cService.GetNomVSCompRequest request);
        
        // CODEGEN: Generating message contract since element name GUID from namespace http://weborder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetLaminaVSColor", ReplyAction="*")]
        OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorResponse GetLaminaVSColor(OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetLaminaVSColor", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorResponse> GetLaminaVSColorAsync(OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorRequest request);
        
        // CODEGEN: Generating message contract since element name GUID from namespace http://weborder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetComplectationPrice", ReplyAction="*")]
        OrdersPortal.Services.WebOrder1cService.GetComplectationPriceResponse GetComplectationPrice(OrdersPortal.Services.WebOrder1cService.GetComplectationPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetComplectationPrice", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetComplectationPriceResponse> GetComplectationPriceAsync(OrdersPortal.Services.WebOrder1cService.GetComplectationPriceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:CreateDocument", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        int CreateDocument(long OrderId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:CreateDocument", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        System.Threading.Tasks.Task<int> CreateDocumentAsync(long OrderId);
        
        // CODEGEN: Generating message contract since element name PicGUID from namespace http://weborder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetLamina", ReplyAction="*")]
        OrdersPortal.Services.WebOrder1cService.GetLaminaResponse GetLamina(OrdersPortal.Services.WebOrder1cService.GetLaminaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetLamina", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetLaminaResponse> GetLaminaAsync(OrdersPortal.Services.WebOrder1cService.GetLaminaRequest request);
        
        // CODEGEN: Generating message contract since element name kontr_kod from namespace http://weborder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetAdvanceContractSumm", ReplyAction="*")]
        OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummResponse GetAdvanceContractSumm(OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:GetAdvanceContractSumm", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummResponse> GetAdvanceContractSummAsync(OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummRequest request);
        
        // CODEGEN: Generating message contract since element name Data from namespace http://weborder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:CreatePaymentDocument", ReplyAction="*")]
        OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentResponse CreatePaymentDocument(OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:CreatePaymentDocument", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentResponse> CreatePaymentDocumentAsync(OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentRequest request);
        
        // CODEGEN: Generating message contract since element name kontr_kod from namespace http://weborder is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:fin_section", ReplyAction="*")]
        OrdersPortal.Services.WebOrder1cService.fin_sectionResponse fin_section(OrdersPortal.Services.WebOrder1cService.fin_sectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://weborder#WebOrder:fin_section", ReplyAction="*")]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.fin_sectionResponse> fin_sectionAsync(OrdersPortal.Services.WebOrder1cService.fin_sectionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNomenklaturaGroupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNomenklaturaGroup", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupRequestBody Body;
        
        public GetNomenklaturaGroupRequest() {
        }
        
        public GetNomenklaturaGroupRequest(OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNomenklaturaGroupRequestBody {
        
        public GetNomenklaturaGroupRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNomenklaturaGroupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNomenklaturaGroupResponse", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupResponseBody Body;
        
        public GetNomenklaturaGroupResponse() {
        }
        
        public GetNomenklaturaGroupResponse(OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class GetNomenklaturaGroupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OrdersPortal.Services.WebOrder1cService.group_list @return;
        
        public GetNomenklaturaGroupResponseBody() {
        }
        
        public GetNomenklaturaGroupResponseBody(OrdersPortal.Services.WebOrder1cService.group_list @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComplectationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComplectation", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetComplectationRequestBody Body;
        
        public GetComplectationRequest() {
        }
        
        public GetComplectationRequest(OrdersPortal.Services.WebOrder1cService.GetComplectationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetComplectationRequestBody {
        
        public GetComplectationRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComplectationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComplectationResponse", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetComplectationResponseBody Body;
        
        public GetComplectationResponse() {
        }
        
        public GetComplectationResponse(OrdersPortal.Services.WebOrder1cService.GetComplectationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class GetComplectationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OrdersPortal.Services.WebOrder1cService.complectations_list @return;
        
        public GetComplectationResponseBody() {
        }
        
        public GetComplectationResponseBody(OrdersPortal.Services.WebOrder1cService.complectations_list @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNomenklaturaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNomenklatura", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetNomenklaturaRequestBody Body;
        
        public GetNomenklaturaRequest() {
        }
        
        public GetNomenklaturaRequest(OrdersPortal.Services.WebOrder1cService.GetNomenklaturaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNomenklaturaRequestBody {
        
        public GetNomenklaturaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNomenklaturaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNomenklaturaResponse", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetNomenklaturaResponseBody Body;
        
        public GetNomenklaturaResponse() {
        }
        
        public GetNomenklaturaResponse(OrdersPortal.Services.WebOrder1cService.GetNomenklaturaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class GetNomenklaturaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OrdersPortal.Services.WebOrder1cService.nom_list @return;
        
        public GetNomenklaturaResponseBody() {
        }
        
        public GetNomenklaturaResponseBody(OrdersPortal.Services.WebOrder1cService.nom_list @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNomVSCompRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNomVSComp", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetNomVSCompRequestBody Body;
        
        public GetNomVSCompRequest() {
        }
        
        public GetNomVSCompRequest(OrdersPortal.Services.WebOrder1cService.GetNomVSCompRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNomVSCompRequestBody {
        
        public GetNomVSCompRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNomVSCompResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNomVSCompResponse", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetNomVSCompResponseBody Body;
        
        public GetNomVSCompResponse() {
        }
        
        public GetNomVSCompResponse(OrdersPortal.Services.WebOrder1cService.GetNomVSCompResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class GetNomVSCompResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OrdersPortal.Services.WebOrder1cService.nom_vs_comp_list @return;
        
        public GetNomVSCompResponseBody() {
        }
        
        public GetNomVSCompResponseBody(OrdersPortal.Services.WebOrder1cService.nom_vs_comp_list @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLaminaVSColorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLaminaVSColor", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorRequestBody Body;
        
        public GetLaminaVSColorRequest() {
        }
        
        public GetLaminaVSColorRequest(OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class GetLaminaVSColorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GUID;
        
        public GetLaminaVSColorRequestBody() {
        }
        
        public GetLaminaVSColorRequestBody(string GUID) {
            this.GUID = GUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLaminaVSColorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLaminaVSColorResponse", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorResponseBody Body;
        
        public GetLaminaVSColorResponse() {
        }
        
        public GetLaminaVSColorResponse(OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class GetLaminaVSColorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OrdersPortal.Services.WebOrder1cService.nom_list @return;
        
        public GetLaminaVSColorResponseBody() {
        }
        
        public GetLaminaVSColorResponseBody(OrdersPortal.Services.WebOrder1cService.nom_list @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComplectationPriceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComplectationPrice", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetComplectationPriceRequestBody Body;
        
        public GetComplectationPriceRequest() {
        }
        
        public GetComplectationPriceRequest(OrdersPortal.Services.WebOrder1cService.GetComplectationPriceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class GetComplectationPriceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long Width;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public long Height;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ArrayGUID;
        
        public GetComplectationPriceRequestBody() {
        }
        
        public GetComplectationPriceRequestBody(string GUID, long Width, long Height, string ArrayGUID) {
            this.GUID = GUID;
            this.Width = Width;
            this.Height = Height;
            this.ArrayGUID = ArrayGUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetComplectationPriceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetComplectationPriceResponse", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetComplectationPriceResponseBody Body;
        
        public GetComplectationPriceResponse() {
        }
        
        public GetComplectationPriceResponse(OrdersPortal.Services.WebOrder1cService.GetComplectationPriceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class GetComplectationPriceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.Nullable<double> @return;
        
        public GetComplectationPriceResponseBody() {
        }
        
        public GetComplectationPriceResponseBody(System.Nullable<double> @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLaminaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLamina", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetLaminaRequestBody Body;
        
        public GetLaminaRequest() {
        }
        
        public GetLaminaRequest(OrdersPortal.Services.WebOrder1cService.GetLaminaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class GetLaminaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string PicGUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CompGUID;
        
        public GetLaminaRequestBody() {
        }
        
        public GetLaminaRequestBody(string PicGUID, string CompGUID) {
            this.PicGUID = PicGUID;
            this.CompGUID = CompGUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLaminaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLaminaResponse", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetLaminaResponseBody Body;
        
        public GetLaminaResponse() {
        }
        
        public GetLaminaResponse(OrdersPortal.Services.WebOrder1cService.GetLaminaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class GetLaminaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string @return;
        
        public GetLaminaResponseBody() {
        }
        
        public GetLaminaResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdvanceContractSummRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdvanceContractSumm", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummRequestBody Body;
        
        public GetAdvanceContractSummRequest() {
        }
        
        public GetAdvanceContractSummRequest(OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class GetAdvanceContractSummRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string kontr_kod;
        
        public GetAdvanceContractSummRequestBody() {
        }
        
        public GetAdvanceContractSummRequestBody(string kontr_kod) {
            this.kontr_kod = kontr_kod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAdvanceContractSummResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAdvanceContractSummResponse", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummResponseBody Body;
        
        public GetAdvanceContractSummResponse() {
        }
        
        public GetAdvanceContractSummResponse(OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class GetAdvanceContractSummResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public OrdersPortal.Services.WebOrder1cService.ContractSumm @return;
        
        public GetAdvanceContractSummResponseBody() {
        }
        
        public GetAdvanceContractSummResponseBody(OrdersPortal.Services.WebOrder1cService.ContractSumm @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePaymentDocumentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePaymentDocument", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentRequestBody Body;
        
        public CreatePaymentDocumentRequest() {
        }
        
        public CreatePaymentDocumentRequest(OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class CreatePaymentDocumentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public OrdersPortal.Services.WebOrder1cService.PaymentDocumentDataList Data;
        
        public CreatePaymentDocumentRequestBody() {
        }
        
        public CreatePaymentDocumentRequestBody(OrdersPortal.Services.WebOrder1cService.PaymentDocumentDataList Data) {
            this.Data = Data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePaymentDocumentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePaymentDocumentResponse", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentResponseBody Body;
        
        public CreatePaymentDocumentResponse() {
        }
        
        public CreatePaymentDocumentResponse(OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class CreatePaymentDocumentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public string @return;
        
        public CreatePaymentDocumentResponseBody() {
        }
        
        public CreatePaymentDocumentResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fin_sectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fin_section", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.fin_sectionRequestBody Body;
        
        public fin_sectionRequest() {
        }
        
        public fin_sectionRequest(OrdersPortal.Services.WebOrder1cService.fin_sectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class fin_sectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string kontr_kod;
        
        public fin_sectionRequestBody() {
        }
        
        public fin_sectionRequestBody(string kontr_kod) {
            this.kontr_kod = kontr_kod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fin_sectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fin_sectionResponse", Namespace="http://weborder", Order=0)]
        public OrdersPortal.Services.WebOrder1cService.fin_sectionResponseBody Body;
        
        public fin_sectionResponse() {
        }
        
        public fin_sectionResponse(OrdersPortal.Services.WebOrder1cService.fin_sectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://weborder")]
    public partial class fin_sectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public fin_sectionResponseBody() {
        }
        
        public fin_sectionResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebOrderPortTypeChannel : OrdersPortal.Services.WebOrder1cService.WebOrderPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebOrderPortTypeClient : System.ServiceModel.ClientBase<OrdersPortal.Services.WebOrder1cService.WebOrderPortType>, OrdersPortal.Services.WebOrder1cService.WebOrderPortType {
        
        public WebOrderPortTypeClient() {
        }
        
        public WebOrderPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebOrderPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebOrderPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebOrderPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupResponse OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetNomenklaturaGroup(OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupRequest request) {
            return base.Channel.GetNomenklaturaGroup(request);
        }
        
        public OrdersPortal.Services.WebOrder1cService.group_list GetNomenklaturaGroup() {
            OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupRequestBody();
            OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupResponse retVal = ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetNomenklaturaGroup(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupResponse> OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetNomenklaturaGroupAsync(OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupRequest request) {
            return base.Channel.GetNomenklaturaGroupAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupResponse> GetNomenklaturaGroupAsync() {
            OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetNomenklaturaGroupRequestBody();
            return ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetNomenklaturaGroupAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebOrder1cService.GetComplectationResponse OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetComplectation(OrdersPortal.Services.WebOrder1cService.GetComplectationRequest request) {
            return base.Channel.GetComplectation(request);
        }
        
        public OrdersPortal.Services.WebOrder1cService.complectations_list GetComplectation() {
            OrdersPortal.Services.WebOrder1cService.GetComplectationRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetComplectationRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetComplectationRequestBody();
            OrdersPortal.Services.WebOrder1cService.GetComplectationResponse retVal = ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetComplectation(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetComplectationResponse> OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetComplectationAsync(OrdersPortal.Services.WebOrder1cService.GetComplectationRequest request) {
            return base.Channel.GetComplectationAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetComplectationResponse> GetComplectationAsync() {
            OrdersPortal.Services.WebOrder1cService.GetComplectationRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetComplectationRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetComplectationRequestBody();
            return ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetComplectationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebOrder1cService.GetNomenklaturaResponse OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetNomenklatura(OrdersPortal.Services.WebOrder1cService.GetNomenklaturaRequest request) {
            return base.Channel.GetNomenklatura(request);
        }
        
        public OrdersPortal.Services.WebOrder1cService.nom_list GetNomenklatura() {
            OrdersPortal.Services.WebOrder1cService.GetNomenklaturaRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetNomenklaturaRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetNomenklaturaRequestBody();
            OrdersPortal.Services.WebOrder1cService.GetNomenklaturaResponse retVal = ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetNomenklatura(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetNomenklaturaResponse> OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetNomenklaturaAsync(OrdersPortal.Services.WebOrder1cService.GetNomenklaturaRequest request) {
            return base.Channel.GetNomenklaturaAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetNomenklaturaResponse> GetNomenklaturaAsync() {
            OrdersPortal.Services.WebOrder1cService.GetNomenklaturaRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetNomenklaturaRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetNomenklaturaRequestBody();
            return ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetNomenklaturaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebOrder1cService.GetNomVSCompResponse OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetNomVSComp(OrdersPortal.Services.WebOrder1cService.GetNomVSCompRequest request) {
            return base.Channel.GetNomVSComp(request);
        }
        
        public OrdersPortal.Services.WebOrder1cService.nom_vs_comp_list GetNomVSComp() {
            OrdersPortal.Services.WebOrder1cService.GetNomVSCompRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetNomVSCompRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetNomVSCompRequestBody();
            OrdersPortal.Services.WebOrder1cService.GetNomVSCompResponse retVal = ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetNomVSComp(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetNomVSCompResponse> OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetNomVSCompAsync(OrdersPortal.Services.WebOrder1cService.GetNomVSCompRequest request) {
            return base.Channel.GetNomVSCompAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetNomVSCompResponse> GetNomVSCompAsync() {
            OrdersPortal.Services.WebOrder1cService.GetNomVSCompRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetNomVSCompRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetNomVSCompRequestBody();
            return ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetNomVSCompAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorResponse OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetLaminaVSColor(OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorRequest request) {
            return base.Channel.GetLaminaVSColor(request);
        }
        
        public OrdersPortal.Services.WebOrder1cService.nom_list GetLaminaVSColor(string GUID) {
            OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorRequestBody();
            inValue.Body.GUID = GUID;
            OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorResponse retVal = ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetLaminaVSColor(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorResponse> OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetLaminaVSColorAsync(OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorRequest request) {
            return base.Channel.GetLaminaVSColorAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorResponse> GetLaminaVSColorAsync(string GUID) {
            OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetLaminaVSColorRequestBody();
            inValue.Body.GUID = GUID;
            return ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetLaminaVSColorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebOrder1cService.GetComplectationPriceResponse OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetComplectationPrice(OrdersPortal.Services.WebOrder1cService.GetComplectationPriceRequest request) {
            return base.Channel.GetComplectationPrice(request);
        }
        
        public System.Nullable<double> GetComplectationPrice(string GUID, long Width, long Height, string ArrayGUID) {
            OrdersPortal.Services.WebOrder1cService.GetComplectationPriceRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetComplectationPriceRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetComplectationPriceRequestBody();
            inValue.Body.GUID = GUID;
            inValue.Body.Width = Width;
            inValue.Body.Height = Height;
            inValue.Body.ArrayGUID = ArrayGUID;
            OrdersPortal.Services.WebOrder1cService.GetComplectationPriceResponse retVal = ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetComplectationPrice(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetComplectationPriceResponse> OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetComplectationPriceAsync(OrdersPortal.Services.WebOrder1cService.GetComplectationPriceRequest request) {
            return base.Channel.GetComplectationPriceAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetComplectationPriceResponse> GetComplectationPriceAsync(string GUID, long Width, long Height, string ArrayGUID) {
            OrdersPortal.Services.WebOrder1cService.GetComplectationPriceRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetComplectationPriceRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetComplectationPriceRequestBody();
            inValue.Body.GUID = GUID;
            inValue.Body.Width = Width;
            inValue.Body.Height = Height;
            inValue.Body.ArrayGUID = ArrayGUID;
            return ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetComplectationPriceAsync(inValue);
        }
        
        public int CreateDocument(long OrderId) {
            return base.Channel.CreateDocument(OrderId);
        }
        
        public System.Threading.Tasks.Task<int> CreateDocumentAsync(long OrderId) {
            return base.Channel.CreateDocumentAsync(OrderId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebOrder1cService.GetLaminaResponse OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetLamina(OrdersPortal.Services.WebOrder1cService.GetLaminaRequest request) {
            return base.Channel.GetLamina(request);
        }
        
        public string GetLamina(string PicGUID, string CompGUID) {
            OrdersPortal.Services.WebOrder1cService.GetLaminaRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetLaminaRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetLaminaRequestBody();
            inValue.Body.PicGUID = PicGUID;
            inValue.Body.CompGUID = CompGUID;
            OrdersPortal.Services.WebOrder1cService.GetLaminaResponse retVal = ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetLamina(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetLaminaResponse> OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetLaminaAsync(OrdersPortal.Services.WebOrder1cService.GetLaminaRequest request) {
            return base.Channel.GetLaminaAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetLaminaResponse> GetLaminaAsync(string PicGUID, string CompGUID) {
            OrdersPortal.Services.WebOrder1cService.GetLaminaRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetLaminaRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetLaminaRequestBody();
            inValue.Body.PicGUID = PicGUID;
            inValue.Body.CompGUID = CompGUID;
            return ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetLaminaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummResponse OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetAdvanceContractSumm(OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummRequest request) {
            return base.Channel.GetAdvanceContractSumm(request);
        }
        
        public OrdersPortal.Services.WebOrder1cService.ContractSumm GetAdvanceContractSumm(string kontr_kod) {
            OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummRequestBody();
            inValue.Body.kontr_kod = kontr_kod;
            OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummResponse retVal = ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetAdvanceContractSumm(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummResponse> OrdersPortal.Services.WebOrder1cService.WebOrderPortType.GetAdvanceContractSummAsync(OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummRequest request) {
            return base.Channel.GetAdvanceContractSummAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummResponse> GetAdvanceContractSummAsync(string kontr_kod) {
            OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummRequest inValue = new OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.GetAdvanceContractSummRequestBody();
            inValue.Body.kontr_kod = kontr_kod;
            return ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).GetAdvanceContractSummAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentResponse OrdersPortal.Services.WebOrder1cService.WebOrderPortType.CreatePaymentDocument(OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentRequest request) {
            return base.Channel.CreatePaymentDocument(request);
        }
        
        public string CreatePaymentDocument(OrdersPortal.Services.WebOrder1cService.PaymentDocumentDataList Data) {
            OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentRequest inValue = new OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentRequestBody();
            inValue.Body.Data = Data;
            OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentResponse retVal = ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).CreatePaymentDocument(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentResponse> OrdersPortal.Services.WebOrder1cService.WebOrderPortType.CreatePaymentDocumentAsync(OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentRequest request) {
            return base.Channel.CreatePaymentDocumentAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentResponse> CreatePaymentDocumentAsync(OrdersPortal.Services.WebOrder1cService.PaymentDocumentDataList Data) {
            OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentRequest inValue = new OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.CreatePaymentDocumentRequestBody();
            inValue.Body.Data = Data;
            return ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).CreatePaymentDocumentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OrdersPortal.Services.WebOrder1cService.fin_sectionResponse OrdersPortal.Services.WebOrder1cService.WebOrderPortType.fin_section(OrdersPortal.Services.WebOrder1cService.fin_sectionRequest request) {
            return base.Channel.fin_section(request);
        }
        
        public bool fin_section(string kontr_kod) {
            OrdersPortal.Services.WebOrder1cService.fin_sectionRequest inValue = new OrdersPortal.Services.WebOrder1cService.fin_sectionRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.fin_sectionRequestBody();
            inValue.Body.kontr_kod = kontr_kod;
            OrdersPortal.Services.WebOrder1cService.fin_sectionResponse retVal = ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).fin_section(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.fin_sectionResponse> OrdersPortal.Services.WebOrder1cService.WebOrderPortType.fin_sectionAsync(OrdersPortal.Services.WebOrder1cService.fin_sectionRequest request) {
            return base.Channel.fin_sectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<OrdersPortal.Services.WebOrder1cService.fin_sectionResponse> fin_sectionAsync(string kontr_kod) {
            OrdersPortal.Services.WebOrder1cService.fin_sectionRequest inValue = new OrdersPortal.Services.WebOrder1cService.fin_sectionRequest();
            inValue.Body = new OrdersPortal.Services.WebOrder1cService.fin_sectionRequestBody();
            inValue.Body.kontr_kod = kontr_kod;
            return ((OrdersPortal.Services.WebOrder1cService.WebOrderPortType)(this)).fin_sectionAsync(inValue);
        }
    }
}
